apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zakaat-app
spec:
  destination:
    name: ""
    namespace: "default"
    server: https://kubernetes.default.svc
  source:
    path: kubernetes/production
    repoURL: https://github.com/SadiqVali786/zakaat-micro-services.git
    targetRevision: HEAD
    directory:
      recurse: true
      jsonnet:
        extVars: []
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
