apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: zakaat-microservices-cluster
  region: ap-south-1
vpc:
  nat:
    gateway: Single  # <-- Adds NAT for private Pods
nodeGroups:
  - name: zakaat-microservices-nodes
    instanceType: t3.medium
    desiredCapacity: 2
    privateNetworking: true