apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: zakaat-microservices-cluster
  region: ap-south-1
vpc:
  nat:
    gateway: Single
nodeGroups:
  - name: zakaat-microservices-nodes
    instanceType: t3.medium
    desiredCapacity: 1
    privateNetworking: true
    