apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zakaat-nginx-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"   # 60 minutes (WebSocket idle time)
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"   # 60 minutes
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"  # 30 seconds (initial connection time)
    nginx.ingress.kubernetes.io/upgrade: "websocket"
    # nginx.ingress.kubernetes.io/connection-proxy-header: "upgrade"
    # nginx.ingress.kubernetes.io/websocket-services: "web-sockets-be,webrtc-signalling-be"
spec:
  ingressClassName: nginx
  rules:
    - host: zakaat.sadiqvali.in
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nextjs-web-app
                port:
                  number: 80
    - host: payments.sadiqvali.in
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: razorpay-payments-be
                port:
                  number: 80
    - host: signalling.sadiqvali.in
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: webrtc-signalling-be
                port:
                  number: 80
    - host: websockets.sadiqvali.in
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-sockets-be
                port:
                  number: 80
