export const config = {
  PORT: Number(process.env.API_GATEWAY_PORT),
  NEXTJS_WEB_APP_SERVICE_URL: process.env.NEXTJS_WEB_APP_SERVICE_URL!,
  WEBRTC_SIGNALLING_SERVER_BE_SERVICE_URL:
    process.env.WEBRTC_SIGNALLING_SERVER_BE_SERVICE_URL!,
  RAZORPAY_PAYMENTS_BE_SERVICE_URL:
    process.env.RAZORPAY_PAYMENTS_BE_SERVICE_URL!,
  WEB_SOCKETS_BE_SERVICE_URL: process.env.WEB_SOCKETS_BE_SERVICE_URL!,
};
